name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          port: ${{ secrets.VM_PORT }}
          key: ${{ secrets.VM_SSH_KEY }}

          script: |

            cd /var/www/portal/Backend

            echo "Atualizando código..."

            git pull origin main

            echo "Reconstruindo containers..."

            docker compose up -d --build

            echo "Removendo imagens antigas..."

            docker image prune -f

            echo "Deploy finalizado!"